### ISSUE TITLE
How Does this Use FileTable Since No Data in WebApiUploads?

### ISSUE THREAD

**Issue by keithnicholson** [damienbod/AspNetCoreFileUploadFileTable#4]
Hi!  I've downloaded your latest update to EF Core 2.1 after reading your blog.  However, I don't think this actually works as intended.  I was able to make the solution appear to work after a minor change in the UploadFiles method of the FilesUploadController due to Path.Combine seeing the second argument as a full path and then ignoring the first argument:

` var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parsefile.ContentDisposition).FileName.ToString().Trim('"'))`

What I noticed is that the extension method SaveAsAsync only streams the file to the folder provided in the configuration directly using System.IO.  It has nothing to do with SQL Server and FileTable.  After loading the file to the directory and being able to download it through the MVC UI, there is no entry however in the WebApiUploads table.

I hope we have a chance to discuss this.

**Comment by damienbod** [comment]
Hi @keithnicholson 

Thanks for your feedback. This was to most efficient way I found to do this. I could also do an SQL insert, but it was slower. I created the helper view so that the meta data for the files can be loaded without loading the files. This way gave the best performance. When I load using the FileTable directly, the performance was worse. 

If you have ways of improving this, I would be very grateful.

Thanks for your feeback and greetings Damein

**Comment by keithnicholson** [comment]
Thanks for replying so quickly.   I'm going to be looking into this during some off time over the next few weeks.  My concern is for now that others may think they are using the FileTable, but they are not.  So, looking at the blog, all of the references to FileTable and the folder needed in the creation of the database is not needed.  I'll validate this soon, but these are my key thoughts:

- Ignore changing the filestream_access_level setting to 2

- In the creation of the Database ignore the FILESTREAM creation
`FILEGROUP FTFG CONTAINS FILESTREAM
(NAME = WebApiFileTableFS,
FILENAME='C:\damienbod\WebApiFileTable\FS')
…
WITH FILESTREAM (NON_TRANSACTED_ACCESS = FULL,
DIRECTORY_NAME = N'WebApiFileTable');
`
- Skip the creation of the WebApiUploads FileTable

- Create your path where every you wish and set in your config file for the ServerUploadFolder

- Still create your FileDescriptions table in EFCore and in the DB

I think this will still give you the same results.

I'll submit more documentation on this soon.  But my key goal is take your idea and for you and I, an hopefully others to make if work somehow.  The challenge is that the EF Team has marked this a Futures requirement as it will not work with LINUX systems today and they have a greater focus on getting EF to work fully with SQL Server on LINUX before looking at features that are Windows specific right.  See [corefx issues #15652](https://github.com/dotnet/corefx/issues/15652).

Peace,
Keith
