### ISSUE TITLE
AllUploadedFiles.cs not found

### ISSUE THREAD

**Issue by Alexgodoroja** [damienbod/AspNetCoreFileUploadFileTable#7]
I observed that you added in ViewAllFiles View DataAccess.Model.AllUploadedFiles but in the Model folder there is no file. Could you please add it with all properties used (fileShortDescriptions etc) in your GitHub Code section?
Many thanks
@damienbod

**Comment by damienbod** [comment]
@Alexgodoroja thanks, I'll fix this, was planning on updating this to .NET 3.0 as well

**Comment by Alexgodoroja** [comment]
@damienbod No problem! I really did not know how to create the class for the ViewAllFiles View, if you can add it it would be amazing!
Thank you kindly,
Alex

**Comment by damienbod** [comment]
Should have been there. I moved it to a separate file

https://github.com/damienbod/AspNetCoreFileUploadFileTable/blob/master/src/DataAccess/Model/AllUploadedFiles.cs
